from django.urls import path, include
from rest_framework.routers import DefaultRouter
from . import views
from .views import login_user, get_user_info, register_user
from rest_framework_simplejwt.views import TokenRefreshView

# Instantiate the DefaultRouter from Django Rest Framework (DRF)
router = DefaultRouter()

# Register ViewSets with the router to automatically generate URLs for CRUD operations
router.register(r"users", views.UserViewSet, basename="user")  # User-related endpoints
router.register(r"movies", views.MovieViewSet, basename="movie")  # Movie-related endpoints
router.register(r"sessions", views.SessionViewSet, basename="session")  # Session-related endpoints
router.register(r"room", views.RoomViewSet, basename="room")  # Room-related endpoints
router.register(r"basket", views.BasketViewSet, basename="basket")  # Basket-related endpoints

# Define the URL patterns for the application
urlpatterns = [
    # Include all URLs generated by the router
    path("", include(router.urls)),

    # Payment-related endpoints
    path("payment/checkout/", views.create_checkout_session, name="create_checkout_session"),  # Create a checkout session
    path("payment/success/", views.payment_success, name="payment_success"),  # Handle successful payment
    path("payment/cancel/", views.payment_cancel, name="payment_cancel"),  # Handle canceled payment

    # Authentication-related endpoints
    path('auth/login/', login_user, name='login'),  # User login endpoint
    path('auth/user/', get_user_info, name='user_info'),  # Get logged-in user information
    path('auth/refresh/', TokenRefreshView.as_view(), name='token_refresh'),  # Refresh JWT token
    path("auth/register/", register_user, name="register_user"),  # User registration endpoint
]
